.github/workflows/code-analysis.yml

Reverts Altinn/app-template-dotnet#10

Revert "Use pull_request_target in workflow"

---

src/Altinn.App.Api/Controllers/RedirectController.cs
src/App.IntegrationTests/ApiTests/RedirectApiTest.cs

Add error handling if string is not base64 encoded

Change redirect url from string to base64 encoded string.

---

.github/workflows/code-analysis.yml
.github/workflows/test-and-analyze-fork.yml
.github/workflows/test-and-analyze.yml
src/Altinn.App.Common/Helpers/JsonHelper.cs
src/Altinn.App.Common/Process/BpmnReader.cs
src/Altinn.App.PlatformServices/Implementation/AppBase.cs
src/Altinn.App.PlatformServices/Implementation/AppResourcesSI.cs

Produces a comment on external PRs like the one below. PR by contributers is analyzed by sonarcloud

Separate workflow for PR from foks

---

src/Altinn.App.Api/Altinn.App.Api.csproj
src/Altinn.App.Common/Altinn.App.Common.csproj
src/Altinn.App.PlatformServices/Altinn.App.PlatformServices.csproj
src/App/App.csproj

This uses the 4.27.0 version of the app template introducing secure options endpoint.

feat: use version 4.27.0 of app template

---

src/Altinn.App.Api/Altinn.App.Api.csproj
src/Altinn.App.Common/Altinn.App.Common.csproj
src/Altinn.App.PlatformServices/Altinn.App.PlatformServices.csproj
src/deployment/Chart.yaml
src/deployment/values.yaml

#50
Final nugets
Readiness and liveness probe enabled by default

Finalize liveness and readiness probe with final nuget v4.30.0

---

src/App/App.csproj

Related to [#5623](https://github.com/Altinn/altinn-studio/issues/5623)

Update project to latest app template

---

src/Altinn.App.Api/Altinn.App.Api.csproj
src/Altinn.App.Common/Altinn.App.Common.csproj
src/Altinn.App.PlatformServices/Altinn.App.PlatformServices.csproj
src/Altinn.App.PlatformServices/Implementation/AppBase.cs

https://github.com/Altinn/altinn-studio/issues/8332
Getting eFormidling changes into app template without requiring breaking changes.
1. Review this PR. 
2. Push alpha nugets
3. Test functionality
4. Push final nugets
5. Close PR without merge
6. From main - create new PR. push new alpha of v5.0.0 with eFormidling changes.

shipment type for DPF included

---

src/Altinn.App.Api/Altinn.App.Api.csproj
src/Altinn.App.Common/Altinn.App.Common.csproj
src/Altinn.App.PlatformServices/Altinn.App.PlatformServices.csproj
src/Altinn.App.PlatformServices/Implementation/AppBase.cs
src/App.IntegrationTests/Data/apps/ttd/eformidling-app/config/applicationmetadata.json

Fixes #altinn/altinn-studio#8332
Duplicating changes made to release/v4

Merged changes from 3.34.1

---

src/Altinn.App.PlatformServices/Configuration/GeneralSettings.cs
src/Altinn.App.PlatformServices/Implementation/ValidationAppSI.cs
src/Altinn.App.PlatformServices/Models/Validation/ValidationIssueSeverity.cs
src/App.IntegrationTests/ApiTests/ValidationApiTest.cs
src/App.IntegrationTests/Data/Instances/tdd/custom-validation/1337/182e053b-3c74-46d4-92ec-a2828289a877/7dfeffd1-1750-4e4a-8107-c6741e05d2a9.json
src/App.IntegrationTests/Data/Instances/tdd/custom-validation/1337/182e053b-3c74-46d4-92ec-a2828289a877/blob/7dfeffd1-1750-4e4a-8107-c6741e05d2a9
src/App.IntegrationTests/Data/apps/tdd/custom-validation/logic/Validation/ValidationHandler.cs

Backend changes needed to support https://github.com/Altinn/app-frontend-react/issues/19. Extends existing support for [soft validations](https://docs.altinn.studio/app/development/logic/validation/#myk-validering) with `success` and `info` messages.

Extend soft validations

---

src/Altinn.App.Api/Altinn.App.Api.csproj
src/Altinn.App.Common/Altinn.App.Common.csproj
src/Altinn.App.PlatformServices/Altinn.App.PlatformServices.csproj
src/App/App.csproj

Final version of 5.2.0 including language selector.
- #8483

Version 5.2.0

---

src/Altinn.App.Api/Altinn.App.Api.csproj
src/Altinn.App.Common/Altinn.App.Common.csproj
src/Altinn.App.PlatformServices/Altinn.App.PlatformServices.csproj
src/Altinn.App.PlatformServices/Implementation/DataClient.cs
src/Altinn.App.PlatformServices/Interface/IData.cs

Incorrect naming of query parameter in dataClient. 
- #66

Bugfix: delayed -> delay

---

src/Altinn.App.Api/Altinn.App.Api.csproj
src/Altinn.App.Common/Altinn.App.Common.csproj
src/Altinn.App.PlatformServices/Altinn.App.PlatformServices.csproj
src/App/App.csproj

Stable nuget packages available for v5.3.0
- #66

Final nugets for v5.3.0

---

src/App.IntegrationTests/App.IntegrationTestsRef.csproj
src/App/App.csproj
src/App/AppRef.csproj
src/Dockerfile

Update app nugets to final version of v6
- #{issue number}

Update app nugets to final version of v6

---

src/App/Program.cs

Note that this PR is against the `chore/90-appbase-simplified` branch

Fix moved namespace

---

src/App/Program.cs

Sync after review of studio update

Add IWebHostEnvironment as param to RegisterCustomAppServices

---

src/App/config/texts/resource.nb.json
src/App/ui/Settings.json
src/App/ui/layouts/receipt.json

Files has gone out of sync. Syncing
Fixes #161 
- #{issue number}

Sync with altinn studio copy

---

src/deployment/Chart.yaml

* Bump helm chart deployment to v2.5.0

Bump deployment chart v2.5.0

---

.github/workflows/add-to-project.yml

Adds all new issues to the team project.
- #{issue number}

Add action to add all new issues to the team project.

---

src/App/ui/footer.json

Default footer is just a link to the standard accessibility statement.
TODO:
- https://github.com/Altinn/app-frontend-react/issues/538
- https://github.com/Altinn/app-frontend-react/issues/110

Added default footer

---

src/deployment/Chart.yaml

Updated charts reference to latest version of the charts. New apps should have a reference to the last version of the helm charts.

Bump to latest chart version

---

src/App/config/texts/resource.nb.json

- https://github.com/Altinn/app-frontend-react/pull/1292

Adding schema for text resource files

---

src/App/config/applicationmetadata.json

Add json schema created in PR:  https://github.com/Altinn/app-frontend-react/pull/1322
Also change spelling of `organization` to `organisation` in order for the template to match storages spelling of the property.

Add json schema to applicationmetadata

---

src/App.IntegrationTests/Data/Instances/tdd/endring-av-navn/1337/d5d5c456-a154-44da-b5da-8d37640635bd.json
src/App.IntegrationTests/Data/apps/tdd/contributer-restriction/config/authorization/policy.xml
src/App.IntegrationTests/Implementation/PdfService/PdfServiceTestsBase.cs
src/App.IntegrationTests/Mocks/Services/DataMockSI.cs

Fixes for renovate/manager-minor-patch branch

---

src/deployment/Chart.yaml

Corrected version number for charts.altinn
- PR itself

fix(Chart): Corrected version number for charts.altinn

---

src/deployment/values.yaml

fix: update outdated doc link
