src/Altinn.App.Api/Altinn.App.Api.csproj
src/Altinn.App.Api/Controllers/OptionsController.cs
src/Altinn.App.Common/Altinn.App.Common.csproj
src/Altinn.App.PlatformServices.Tests/Options/NullInstanceAppOptionsProviderTests.cs
src/Altinn.App.PlatformServices/Altinn.App.PlatformServices.csproj
src/Altinn.App.PlatformServices/Options/NullInstanceAppOptionsProvider.cs
src/App.IntegrationTests/ApiTests/OptionsApiTests.cs

This changes how options are returned when there are no elements in the list. Previously we returned 404 both when we could not find the specified option id and if the specified option id had zero elements. With this change we only return 404 if we can't find the specified option id. For the case of zero elements we just return an empty list.

Change options controller to not return 404 when the list contains zero elements

---

src/Altinn.App.Api/Altinn.App.Api.csproj
src/Altinn.App.Common/Altinn.App.Common.csproj
src/Altinn.App.PlatformServices/Altinn.App.PlatformServices.csproj
src/Altinn.App.PlatformServices/Configuration/CacheSettings.cs
src/Altinn.App.PlatformServices/Decorators/ProfileClientCachingDecorator.cs
src/Altinn.App.PlatformServices/Extensions/ClaimsPrincipalExtensions.cs
src/Altinn.App.PlatformServices/Extensions/ServiceCollectionExtensions.cs
src/Altinn.App.PlatformServices/Implementation/ProcessChangeHandler.cs
src/App.IntegrationTests/DecoratorTests/ProfileTestCachingDecoratorTest.cs
src/App.IntegrationTests/Utils/TestDataUtil.cs

For each generated instance event a lookup is done to find the SSN of the user that triggered the event, and this data is added to the instanceEvent. 
Added caching of userprofile. 
Tips on how to best verify that SSN is  included is appreciated. No obvious way as I see it, except checking incomming events and validating towards userprofile in testdata.
#5751

Add SSN to platformUser in instanceEvents

---

src/Altinn.App.Api/Altinn.App.Api.csproj
src/Altinn.App.Common/Altinn.App.Common.csproj
src/Altinn.App.PlatformServices.Tests/Implementation/PersonClientTests.cs
src/Altinn.App.PlatformServices/Altinn.App.PlatformServices.csproj
src/Altinn.App.PlatformServices/Implementation/PersonClient.cs

Request header values are limited to ASCII characters. Values must be encoded with base64.

Add base64 encoding to lastname parameter

---

src/Altinn.App.PlatformServices/Implementation/PrefillSI.cs
src/Altinn.App.PlatformServices/Interface/IPrefill.cs

Writing prefill code is tedious and error-prone (as the tree might have
been partially constructed). Exposing the inner functionality of
PrefillSI, we can use the same key/value pairs as is used in the prefill
json.
E.g.
```csharp
public async Task DataCreation(Instance instance, object data, Dictionary<string, string> prefill) {
prefillService.PrefillDataModel(data, new Dictionary<string, string> {
{ "a.value", "a" },
{ "b.value", "b" },
// ..
});
await Task.CompletedTask;
}
```

Expose prefill method to user

---

src/App/views/Home/Index.cshtml

The `style` tag is not valid as a direct child of `body` as [per the spec](https://html.spec.whatwg.org/multipage/semantics.html#the-style-element).

fix: style tag is not a valid child of body

---

src/Dockerfile

Short options are good for interactive scripts, but long options are
better in scripts.

Use long options in Dockerfile

---

src/Altinn.App.PlatformServices/Extensions/ClaimsPrincipalExtensions.cs

- All methods follows the same pattern and is easily generalized
- FindFirst returns null when not found, so we don't have to use
HasClaim followed by return null otherwise.
- AltinnCoreClaimType is referenced twice per method, easily leading to
copy/paste errors
- Can use null coalescing return

Reduce some duplication

---

src/Altinn.App.PlatformServices/Extensions/ConfigurationBuilderExtensions.cs

When starting an app with `dotnet run` on my linux host, I got a `System.IO.IOException: Invalid argument` caused by this code starting a recursive file system watch over the whole root filesystem.
After a discussion on slack yesterday, this looked like the best solution, where we'll watch a sub-folder on the root filesystem instead.
Tested with and without this folder and configuration file in place, against a test app, using the release/v4 branch.

Fixing deep fs recursion issue

---

src/Altinn.App.Api/Controllers/DataController.cs
src/Altinn.App.Api/Controllers/InstancesController.cs
src/Altinn.App.Api/Controllers/ProcessController.cs

`LogError` as a special method to log exceptions that is used in many other locations of the project, and should probably be used here as well.

Log exceptions as data instead of string

---

src/Altinn.App.Api/Controllers/InstancesController.cs
src/Altinn.App.Api/Mappers/SimpleInstanceMapper.cs
src/App.IntegrationTests/ApiTests/InstanceApiTest.cs
src/App.IntegrationTests/Data/Instances/ttd/presentationfields-app/1401/8d5a293f-98ed-4c2c-9a6b-3593f49b4d26.json

This caused a null pointer exception in `/{org}/{app}/instances/{instanceOwnerPartyId}/active`
when the instance was initialized from api.

Handle null in lastChangedBy

---

src/Altinn.App.Api/Altinn.App.Api.csproj
src/Altinn.App.Api/Controllers/HomeController.cs
src/Altinn.App.Common/Altinn.App.Common.csproj
src/Altinn.App.PlatformServices/Altinn.App.PlatformServices.csproj

Bugfix for changes made for https://github.com/Altinn/altinn-studio/issues/8403. 
When no `onEntry` property was defined in applicationMetadata, the check for stateless did not work as expected.

Support app metadata without onEntry property

---

src/Altinn.App.Api/Altinn.App.Api.csproj
src/Altinn.App.Common/Altinn.App.Common.csproj
src/Altinn.App.PlatformServices/Altinn.App.PlatformServices.csproj
src/App/App.csproj

This changes the app template to use the 5.1.0 version of the nuget packages, enabling stateless apps without requiring the user to be logged in.

feat: use 5.1.0 version of the app to enable stateless without login feature.

---

src/App/Program.cs

Version 6 of app-template did not call LoadAppCofig. Adds kall to this method to load appsettings if present
- #125

Add call to configBuilder.LoadAppConfig(); to initialize appsettings

---

src/App/Properties/launchSettings.json
src/App/appsettings.json

On startup of apps, the following warning is displayed.
```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
Overriding address(es) 'http://localhost:56227/'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
```
This is caused by specifiying `"applicationUrl": "http://localhost:56227`  in launchSettings.json and 
```
"Kestrel": {
"EndPoints": {
"Http": {
"Url": "http://*:5005"
}
}
}
```
in appsettings.json
~~I propose to remove the wrong declaration in lanuchSettings.json~~
**Edit:**
After testing the docker container, I found that we should rather fix the `Url` in launchSettings.json and remove the `Url` in appsettings.json to remove this warning everywhere.

Remove warning because of double specification of applicationUrl

---

src/App/Properties/launchSettings.json
src/App/appsettings.json
src/Dockerfile

~~Reverts Altinn/app-template-dotnet#155~~
~~removing Kestrel section from appsettings.json results in applications trying to start on port 80 once deployed. 
Ports below 1024 are marked as privileged on linux and non-root users are not allowed to bind to these ports leading to application crash on startup~~
Add config in appsettings back and remove applicationUrl from launchSettings and remove value of ASPNETCORE_URLS in docker image to remove warning both locally and in docker
Fixes #163

Add Kestrel section to appsettings and remove other URL settings

---

src/Dockerfile

I'm opening this mainly because I want to give a heads up on these issues. I'm not in a hurry to have this merged, but it seems wasteful to not share the painful experience of figuring out this.
I tried to work on some sort of automated testing and ran into a really strange issue with dotnet in docker. The docker container did not work with `--env DOTNET_ENVIRONMENT=Development`. After lots of guesswork I found that deleting the `wwwroot` folder fixed the issue. It turns out that when you do a separate `build` step it generates `App.staticwebassets.runtime.json` with full absolute path to the `wwwroot` folder, and it gets included in the `publish` result. In the `build` step the path is `/App/wwwroot`, but in final the name was `/app/wwwroot`.
This fixes 3 issues
* A separate `restore` …

Fix a few issues with the Dockerfile

---

src/App/views/Home/Index.cshtml

In the next release of app-frontend, the font is switched to use Inter, and this font is added directly through app-frontend's css bundle, so a link in app-template is not needed https://github.com/Altinn/app-frontend-react/pull/1173. Therefore, the link to Altinn-DIN should be removed since this will no longer be used.
Fixes #181

Remove link to altinn-din from app-template

---

src/App/views/Home/Index.cshtml

Change of font caused breaking changes. Reverting removal of altinn-din

Revert "Remove link to altinn-din from app-template"

---

src/deployment/Chart.yaml

New apps are deployed with a late version of the helm charts, it should use the newest version avaiable

Latest chart version as default

---

src/deployment/Chart.yaml

* bump helm dependencies chart deployment to v3.2.0
- #{issue number}

chore: bump helm dependency deployment chart v3.2.0

---

src/App/App.csproj

Bumped to latest version, 8.0.0 -> 8.3.5
Made no changes to default app config, as these are minor/patch upgrades and should not be breaking.

chore: bump app lib references to v8.3.5

---

src/Dockerfile

```json
"PdfGeneratorSettings": {
"DisplayFooter": true
}
```
requires globalisation and timezone info in docker images.
This will ensure that new apps gets this setting by default.
```dockerfile
RUN apk add --no-cache icu-libs tzdata
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
```
- https://github.com/Altinn/app-lib-dotnet/pull/792

Update Dockerfile to include timezone and culture information

---

src/App/App.csproj

* As of 8.6 should not have `Swashbuckle.AspNetCore`
* Why is `Microsoft.Extensions.Logging.Debug` there? It's not added 
- N/A

Bump applib, cleanup dependencies
